# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "guard-openscad"
  s.version = "0.1.4"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Caleb Buxton"]
  s.date = "2013-03-08"
  s.description = "Checks syntax of .scad files and generates .stl files."
  s.email = "me@cpb.ca"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md"
  ]
  s.files = [
    ".document",
    ".rspec",
    ".simplecov",
    "Gemfile",
    "Guardfile",
    "LICENSE.txt",
    "README.md",
    "Rakefile",
    "VERSION",
    "features/README.feature",
    "features/step_definitions/.gitkeep",
    "features/step_definitions/README_steps.rb",
    "features/support/env.rb",
    "guard-openscad.gemspec",
    "lib/guard/openscad.rb",
    "lib/guard/openscad/templates/Guardfile",
    "spec/fixtures/scad/cube.scad",
    "spec/guard/openscad_spec.rb",
    "spec/integration/guard/openscad_spec.rb",
    "spec/spec_helper.rb",
    "spec/support/core_ext/hash/except.rb",
    "spec/support/matchers/run_files_matcher.rb"
  ]
  s.homepage = "http://github.com/cpb/guard-openscad"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.23"
  s.summary = "Guard plugin for OpenSCAD"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<growl>, ["~> 1.0"])
      s.add_runtime_dependency(%q<guard>, ["~> 1.6"])
      s.add_runtime_dependency(%q<rb-fsevent>, ["~> 0.9"])
      s.add_runtime_dependency(%q<scad4r>, ["~> 0.3"])
      s.add_development_dependency(%q<aruba>, ["~> 0.5"])
      s.add_development_dependency(%q<cucumber>, ["~> 1.2"])
      s.add_development_dependency(%q<guard-cucumber>, ["~> 1.3"])
      s.add_development_dependency(%q<guard-rspec>, ["~> 2.3"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.8"])
      s.add_development_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_development_dependency(%q<rspec>, ["~> 2.12"])
      s.add_development_dependency(%q<simplecov>, ["~> 0.7"])
      s.add_development_dependency(%q<simplecov-csv>, ["~> 0.1"])
    else
      s.add_dependency(%q<growl>, ["~> 1.0"])
      s.add_dependency(%q<guard>, ["~> 1.6"])
      s.add_dependency(%q<rb-fsevent>, ["~> 0.9"])
      s.add_dependency(%q<scad4r>, ["~> 0.3"])
      s.add_dependency(%q<aruba>, ["~> 0.5"])
      s.add_dependency(%q<cucumber>, ["~> 1.2"])
      s.add_dependency(%q<guard-cucumber>, ["~> 1.3"])
      s.add_dependency(%q<guard-rspec>, ["~> 2.3"])
      s.add_dependency(%q<jeweler>, ["~> 1.8"])
      s.add_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_dependency(%q<rspec>, ["~> 2.12"])
      s.add_dependency(%q<simplecov>, ["~> 0.7"])
      s.add_dependency(%q<simplecov-csv>, ["~> 0.1"])
    end
  else
    s.add_dependency(%q<growl>, ["~> 1.0"])
    s.add_dependency(%q<guard>, ["~> 1.6"])
    s.add_dependency(%q<rb-fsevent>, ["~> 0.9"])
    s.add_dependency(%q<scad4r>, ["~> 0.3"])
    s.add_dependency(%q<aruba>, ["~> 0.5"])
    s.add_dependency(%q<cucumber>, ["~> 1.2"])
    s.add_dependency(%q<guard-cucumber>, ["~> 1.3"])
    s.add_dependency(%q<guard-rspec>, ["~> 2.3"])
    s.add_dependency(%q<jeweler>, ["~> 1.8"])
    s.add_dependency(%q<rdoc>, ["~> 3.12"])
    s.add_dependency(%q<rspec>, ["~> 2.12"])
    s.add_dependency(%q<simplecov>, ["~> 0.7"])
    s.add_dependency(%q<simplecov-csv>, ["~> 0.1"])
  end
end

